---
name: pipelinecomponents

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        run: yamllint .

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    container: pipelinecomponents/markdownlint:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        run: mdl --style all --warnings .
